[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "java -jar app.jar"
healthcheckPath = "/adminsystem/ping"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
JAVA_VERSION = "17"
SPRING_PROFILES_ACTIVE = "railway"
PORT = "8080"
